#!/usr/bin/env ruby

require 'socket'
require_relative '../lib/sslauthserver'

require 'minitest/spec'
require 'minitest/autorun'

describe SSLAuthServer do
  before do
    @certs_dir = "#{File.dirname(__FILE__)}/certs"
    @server_key_path = "#{@certs_dir}/server.key"
    @server_key = OpenSSL::PKey::RSA.new File.read @server_key_path
    @server_cert_path = "#{@certs_dir}/server.pub"
    @server_cert = OpenSSL::X509::Certificate.new File.read @server_cert_path
    @client_ids = [:client1,:client2,:unknown]
    @client_paths = @client_ids.map{|id|["#{@certs_dir}/#{id}.pub",id]}.to_h
    @clients = @client_ids.map{|id|
      [id,
        [[:key,OpenSSL::PKey::RSA], [:pub,OpenSSL::X509::Certificate]].map{|type,cls|
          [type, cls.new(File.read("#{@certs_dir}/#{id}.#{type}"))]}.to_h]}.to_h
  end
  def mkserver_from_certs(auth_client_ids)
    SSLAuthServer.new(TCPServer.new(0), @server_key, @server_cert, @clients.select{|id|auth_client_ids.include?(id)}.map{|id,ssl|[ssl[:pub],id]}.to_h)
  end
  def mkserver_from_paths(auth_client_ids)
    SSLAuthServer.new_from_paths(TCPServer.new(0), @server_key_path, @server_cert_path, @client_paths.select{|_,id|auth_client_ids.include?(id)})
  end
  def try_connect(server, connect_client_id)
    server_thread = Thread.new{ server.accept.client_id }
    context = OpenSSL::SSL::SSLContext.new
    context.verify_mode = OpenSSL::SSL::VERIFY_PEER
    context.cert_store = OpenSSL::X509::Store.new
    context.cert_store.add_cert @server_cert
    context.key = @clients[connect_client_id][:key] if connect_client_id
    context.cert = @clients[connect_client_id][:pub] if connect_client_id
    tcp_socket = TCPSocket.new 'localhost', server.to_io.local_address.ip_port
    client = OpenSSL::SSL::SSLSocket.new tcp_socket, context
    client.connect
    server_thread.join.value
  end
  [:mkserver_from_certs, :mkserver_from_paths].each do |mkserver|
    it "can accept clients via #{mkserver}" do
      try_connect(send(mkserver, [:client1,:client2]),:client1).must_equal :client1
      try_connect(send(mkserver, [:client1,:client2]),:client2).must_equal :client2
    end
    it "can deny unknown client via #{mkserver}" do
      err = proc { try_connect(send(mkserver, [:client1,:client2]),:unknown) }.must_raise OpenSSL::SSL::SSLError
      err.message.must_match /alert unknown ca/
    end
    it "can deny certless client via #{mkserver}" do
      err = proc { try_connect(send(mkserver, [:client1,:client2]),nil) }.must_raise OpenSSL::SSL::SSLError
      err.message.must_match /alert handshake failure/
    end
  end
end
